FROM node:20-alpine as base
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package*.json .
RUN npm i

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY . .
ENV NODE_APP_ENV local

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME 0.0.0.0
CMD [ "npm", "run" , "dev"]
