import DataDisplay from "@/components/displayTable/DataDisplay";
import { DbTypes } from "@/types/ResponseTypes";
import { getData } from "@/utils/FormInputHandling";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Search } from "react-feather";

export default function Home({
  data,
  hasMore,
  currentPage,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const router = useRouter();

  const refreshData = () => {
    router.replace(router.asPath);
  };
  useEffect(() => {
    const { type } = router.query;
    if (type === "edit") {
      refreshData();
    }
  }, [router.query]);
  return (
    <>
      <Head>
        <title>Quiz-creator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <nav className="flex justify-between m-2 p-5">
        <div className="bg-[#B52326] text-[#FFFFFF] text-[20px] px-2 py-2 md:px-3 rounded-md md:text-lg">
          <button onClick={() => router.push("/Session?type=create")}>
            + Create Quiz Session
          </button>
        </div>

        <div className="flex items-center border-black border-solid border rounded-md text-md text-[#868585] md:text-md md:w-2/5">
          <Search className="m-2 " />
          <input
            type="text"
            placeholder="Search by CMS_id or Test_name"
            className="flex-grow p-2 rounded-md md:w-2/5 outline-none"
          />
        </div>
      </nav>

      <DataDisplay data={data} hasMore={hasMore} currentPage={currentPage} />
    </>
  );
}

export const getServerSideProps = (async ({ query: { pageNo } }) => {
  const currentPage = Number(pageNo) || 0;

  const { data, hasMore } = await getData(currentPage, 10);

  return {
    props: {
      data,
      hasMore,
      currentPage,
    },
  };
}) satisfies GetServerSideProps<{
  data: DbTypes[];
  hasMore: boolean;
  currentPage: number;
}>;
