import type { Session } from '@/types';
import { displayData } from './ModalData';

describe('displayData activity details', () => {
  it('shows recorded session actors and action timestamps', () => {
    const session = {
      name: 'Audit test',
      platform: 'quiz',
      start_time: '2026-07-22T08:00:00.000Z',
      end_time: '2026-07-22T09:00:00.000Z',
      meta_data: {
        created_by: 'creator@avantifellows.org',
        last_edited_by: 'editor@avantifellows.org',
        last_edited_at: '2026-07-22T08:15:28.971Z',
        last_regenerated_by: 'regenerator@avantifellows.org',
        last_regenerated_at: '2026-07-22T08:20:00.000Z',
      },
    } satisfies Session;

    const activity = displayData(session, []).find((section) => section.title === 'Activity');

    expect(activity?.data.map(({ label, value }) => ({ label, value }))).toEqual(
      expect.arrayContaining([
        { label: 'Created By', value: 'creator@avantifellows.org' },
        { label: 'Last Edited By', value: 'editor@avantifellows.org' },
        { label: 'Last Regenerated By', value: 'regenerator@avantifellows.org' },
      ])
    );
    expect(activity?.data.find((item) => item.label === 'Last Edited At')?.value).toBeTruthy();
    expect(activity?.data.find((item) => item.label === 'Last Regenerated At')?.value).toBeTruthy();
  });

  it('does not add an empty activity section to legacy sessions', () => {
    const session = {
      name: 'Legacy session',
      platform: 'quiz',
      start_time: '2026-07-22T08:00:00.000Z',
      end_time: '2026-07-22T09:00:00.000Z',
      meta_data: {},
    } satisfies Session;

    expect(displayData(session, []).some((section) => section.title === 'Activity')).toBe(false);
  });
});
