#!/bin/sh
# Source NVM if it exists to ensure correct Node/npm version
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Execute lint-staged
npx lint-staged --allow-empty

exit $?
